# Generated by Django 2.1 on 2018-09-18 21:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0021_auto_20180813_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'baglan': None, 'balacan': None, 'cagri': None, 'test_user': None}),
        ),
    ]
