# Generated by Django 2.1 on 2018-09-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0022_auto_20180918_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='text_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
